default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  host: localhost

development:
  database: boacausa_development
  <<: *default

test:
  <<: *default
  database: boacausa_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
